[package]
name = "multi-light"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.140"
yaml-rust2 = "0.10.0"
toml = "0.8.20"
onig = { version = "6.4.0", default-features = false }
